# **Practice Actiivty - Pandas Series**

**Introduction:**
A pandas Series is a one-dimensional array. It holds any data type supported in Python and uses labels to locate each data value for retrieval. These labels form the index, and they can be strings or integers. A Series is the main data structure in the pandas framework for storing one-dimensional data.

**Common methods used with Pandas Series**


Please refer to the [Pandas Series Documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) for a full list of methods and how to implement them.

To complete the problems below we first need to import the Pandas and Numpy libraries. If you haven't already installed them, use pip or conda to install them globally or in your virtual environment.


* The common alias for pandas is pd.  
* The common alias for numpy is np.

In [1]:
import pandas as pd
import numpy as np

**Problem 1**

We can easily convert lists, tuples, dictionaries and numpy arrays into a Pandas Series by directly passing the python object as an arguement to the Series() constructor. We have used the alias pd in the cell above, so we will use pd.Series() to construct our Series object.



*  Convert the 3 objects below into 3 seperate Pandas Series objects.
*  Use the .head() method to see the first 5 items in each Series

In [2]:
mylist = list('abcedfghijklmnopqrstuvwxyz')  # List of individual characters
myarr = np.arange(26)  # NumPy array containing 0 through 25
mydict = dict(zip(mylist, myarr))  # Map each letter to a number

list_series = pd.Series(mylist)
array_series = pd.Series(myarr)
dictionary_series = pd.Series(mydict)

print('List Series:')
display(list_series.head())
print('Array Series:')
display(array_series.head())
print('Dictionary Series:')
display(dictionary_series.head())

List Series:

0    a
1    b
2    c
3    e
4    d
dtype: str

Array Series:

0    0
1    1
2    2
3    3
4    4
dtype: int64

Dictionary Series:

a    0
b    1
c    2
e    3
d    4
dtype: int64

**Problem 2**

We can give a name to our Pandas series as a parameter of our Constructor method.

*   Use the name parameter to add 'alphabet' as the name of our series.
*   Use the .head() method to see the name of our Series displayed

In [3]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'), name='alphabet')
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabet, dtype: str

**Problem 3: Assign a name to the Series**

We can assign a name to a Series after it is created using the `.name` attribute on our Series object.



*   Use the `.name` attribute to add the name 'alphabet1' to the Series object after it has been created.
*   Use the .head() method to verify

In [4]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'alphabet1'
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabet1, dtype: str

**Problem 4**

We can use mathematic operators to perform calculations on two or more series.

*   Create a new object that adds the two series below
*   Create a new object that subtracts the two series below
*   Create a new object that multiplies the two series below
*   Create a new object that divides the two series below

Make sure you display your outputs.

In [5]:
ser1 = pd.Series([2, 4, 6, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 9])

addition = ser1 + ser2
subtraction = ser1 - ser2
multiplication = ser1 * ser2
division = ser1 / ser2

arithmetic_results = pd.DataFrame({
    'addition': addition,
    'subtraction': subtraction,
    'multiplication': multiplication,
    'division': division,
})
arithmetic_results

   addition  subtraction  multiplication  division
0         3            1               2  2.000000
1         7            1              12  1.333333
2        11            1              30  1.200000
3        15            1              56  1.142857
4        19            1              90  1.111111

**Problem 5**

We can use comparison operators to compare elements of two Series.

Use the series below to perform the following:


*   Check if the elements in ser1 are equal to the elements in ser2
*   Check if the elements in ser1 are greater than the elements in ser2
*   Check if the elements in ser1 are less than the elements in ser2

In [6]:
ser1 = pd.Series([2, 4, 5, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 10])

equal_to = ser1 == ser2
greater_than = ser1 > ser2
less_than = ser1 < ser2

comparison_results = pd.DataFrame({
    'equal': equal_to,
    'ser1 > ser2': greater_than,
    'ser1 < ser2': less_than,
})
comparison_results

   equal  ser1 > ser2  ser1 < ser2
0  False         True        False
1  False         True        False
2   True        False        False
3  False         True        False
4   True        False        False

**Problem 6**

We can add additional elements to our Pandas Series. Use the Series below to perform the following:


*   Create a new Series by using the `.concat()` method to add 'penguin' and 'lion' to the Series object
*   Use the `.reset_index()` method to reset the index values.

(Both steps can be done in one line)

In [7]:
ser = pd.Series(['cat', 'dog', 'elephant', 'frog'])
expanded_ser = pd.concat([ser, pd.Series(['penguin', 'lion'])]).reset_index(drop=True)
expanded_ser

0         cat
1         dog
2    elephant
3        frog
4     penguin
5        lion
dtype: str

**Problem 7**

We can customize the index of our Series by using the 'index' paramater in our Series constructor. Use the Series below to peform the following:


*   Set the index to ['A', 'B', 'C', 'D']
*   Use the .reindex() method after the Series object is created to change the order of the index to ['B', 'A', 'D', 'C']

In [8]:
ser = pd.Series(['cat', 'dog', 'elephant', 'frog'], index=['A', 'B', 'C', 'D'])
reindexed_ser = ser.reindex(['B', 'A', 'D', 'C'])
reindexed_ser

B         dog
A         cat
D        frog
C    elephant
dtype: str

**Problem 8**

Find the elements in the first series (ser1) not in the second series (ser2).


*   Use the single square bracket notation and the .isin() method with ser1 to remove the items present in ser2. This will leave us with only the itmes not present in ser2.

In [9]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_only_in_ser1 = ser1[~ser1.isin(ser2)]
items_only_in_ser1

0    1
1    2
2    3
dtype: int64

**Problem 9**

Use the Series below to peform the following:
*   Use a built-in Pandas method to find the mean of the Series
*   Use a built-in Pandas method to find the standard deviation of the Series

In [10]:
ser = pd.Series(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])

mean_value = ser.mean()
standard_deviation = ser.std()
pd.Series({'mean': mean_value, 'standard deviation': standard_deviation})

mean                  4.818182
standard deviation    2.522625
dtype: float64

**Problem 10**

Find the elements in both series that are not in common (remove them if they exist in both).

*   Create a new Series using np.union1d()
*   Create a new Series using np. intersect1d()
*   Use single square bracket notation and the .isin() method to find the final result

In [11]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1, ser2))
intersection = pd.Series(np.intersect1d(ser1, ser2))
symmetric_difference = union[~union.isin(intersection)]
symmetric_difference

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

**Problem 11**

Find the minimum, max, 25th percentile, and 75th percentile in the series.

*   Use np.percentile to find the percentiles above

In [12]:
rng = np.random.default_rng(386)
ser = pd.Series(rng.normal(10, 5, 25))

summary = pd.Series({
    'minimum': np.percentile(ser, 0),
    'maximum': np.percentile(ser, 100),
    '25th percentile': np.percentile(ser, 25),
    '75th percentile': np.percentile(ser, 75),
})
summary

minimum            -1.330674
maximum            18.129029
25th percentile     6.464790
75th percentile    12.702523
dtype: float64

**Problem 12**

Obtain the count of each unique item in the series.


*   Use the .value_counts() method to find the frequency count of each unique item

In [13]:
rng = np.random.default_rng(386)
ser = pd.Series(np.take(list('abcdefgh'), rng.integers(8, size=30)))
frequency_counts = ser.value_counts()
frequency_counts

d    7
b    5
c    4
h    4
g    4
e    4
f    1
a    1
Name: count, dtype: int64

**Problem 13**

Keep the two most frequent items in the series and change all items that are not those two into "Other".



*   Use .isin(), .valuecounts(), and .index() to complete the task above

In [14]:
rng = np.random.default_rng(100)
ser = pd.Series(rng.integers(1, 5, size=12))

top_two_items = ser.value_counts().index[:2]
result = ser.where(ser.isin(top_two_items), 'Other')
result

0         4
1         4
2         1
3     Other
4         1
5     Other
6     Other
7         1
8     Other
9         4
10        4
11    Other
dtype: object

**Problem 14**

Bin the series below into 10 equal deciles and replace the values with the bin name.

*   Use the .qcut() method to complete the task

In [15]:
rng = np.random.default_rng(386)
ser = pd.Series(rng.random(20))
decile_labels = [f'Decile {number}' for number in range(1, 11)]
deciles = pd.qcut(ser, q=10, labels=decile_labels)
deciles

0      Decile 2
1      Decile 3
2      Decile 9
3      Decile 8
4     Decile 10
5      Decile 6
6      Decile 8
7      Decile 4
8      Decile 5
9      Decile 2
10     Decile 7
11     Decile 3
12     Decile 9
13    Decile 10
14     Decile 1
15     Decile 5
16     Decile 6
17     Decile 1
18     Decile 7
19     Decile 4
dtype: category
Categories (10, str): ['Decile 1' < 'Decile 2' < 'Decile 3' < 'Decile 4' ... 'Decile 7' < 'Decile 8' < 'Decile 9' < 'Decile 10']

**Problem 15**

From ser, extract the items at positions in list pos.

*   Use the .take() method to complete the task

In [16]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
selected_items = ser.take(pos)
selected_items

0     a
4     e
8     i
14    o
20    u
dtype: str

**Problem 16**

Stack ser1 and ser2 vertically.

*   Use the .concat() method to complete the task

In [17]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
stacked_series = pd.concat([ser1, ser2], ignore_index=True)
stacked_series

0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object

**Problem 17**

Get the positions of items of ser2 in ser1 as a list.

*   Use list comprehension, pd.Index, and .getloc() to complete the task

In [18]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
positions = [pd.Index(ser1).get_loc(item) for item in ser2]
positions

[5, 4, 0, 8]

**Problem 18**

Caluculate the difference of differences between the consequtive numbers of ser. Dislplay the output as a list.

*   Use the .diff() method to the complete the task

In [19]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
first_differences = ser.diff().tolist()
second_differences = ser.diff().diff().tolist()

print('First differences:', first_differences)
print('Second differences:', second_differences)

First differences: [nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
Second differences: [nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

**Problem 19**

Convert the date-strings to a timeseries.

*   use the .to_datetime() method to complete the task

In [20]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
time_series = pd.to_datetime(ser, format='mixed')
time_series

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[us]

**Problem 20**

Compute the mean of weights of each fruit.

In [21]:
rng = np.random.default_rng(386)
fruit = pd.Series(rng.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

mean_weight_by_fruit = weights.groupby(fruit).mean()
mean_weight_by_fruit

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'apple', 'carrot', 'banana', 'apple', 'carrot', 'apple', 'carrot', 'banana', 'carrot']

apple     4.666667
banana    4.666667
carrot    6.750000
dtype: float64

##**Submission**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.