#**Guided Lab 386.3.10 - Sorting a Pandas DataFrame**

##**Learning Objective:**

In this lab, you will demonstrate how to sort data(column) in a Pandas DataFrame using the **`.sort_values()`** function.

By the end of this lesson, learner will be able to:
-Explain the concept of sorting data in a Pandas DataFrame.
Utilize the .sort_values() function to sort a DataFrame by one or more columns.
- Specify the sorting order (ascending or descending) using the ascending parameter.
- Sort a DataFrame by multiple columns with different sorting orders.
- Apply sorting techniques to real-world data scenarios.

#**Example 1**

You can use **.sort_values()** function to sort values in a DataFrame along either axis (columns or rows). Typically, you want to sort the rows in a DataFrame by the values of one or more columns:

In [1]:
import pandas as pd
# Define a dictionary containing Students data
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}
print("------before -------")
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print(df)
print("------after adding column -------")
# using DataFrame.assign() method adding 'Address' column and equating it to the list
df = df.assign(address = ['NYC', 'NJ', 'CA', 'PA'])
print(df)

------before -------
     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30
------after adding column -------
     Name  Height Qualification  Score 1  Score 2 address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [ ]:
print("------after sorting -------")
print(df.sort_values(by='Score 1', ascending=False))

###**Sort by Two Columns: If you want to sort by multiple columns, then just pass lists as arguments for by and ascending as shown below.**

In [ ]:
print (df.sort_values(by=['Score 1', 'Height'], ascending=[False, True]))



---



---



#**Example 2**

In this example we will use the [car.json](https://drive.google.com/file/d/1sQbulhEOr5NZEFy5zF7g_7z8OFUMkKo7/view?usp=sharing) file:

In [ ]:
import pandas as pd
df_cars = pd.read_json('cars.json')

print("------before -------")
 df_cars.head(15)

------before -------

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS
14,Datsun 1200,35.0,4,72.0,69,1613,18.0,71,Japan,99,TEXAS

In [ ]:
print("------After Sorting -------")
df_cars.sort_values(by=['quantity'], ascending=[True])

------After Sorting -------

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
123,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US,5,OH
112,Ford Mustang II 2+2,25.5,4,140.0,89,2755,15.8,77,US,5,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
121,Ford Ranger,28.0,4,120.0,79,2625,18.6,82,US,7,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...
128,Honda Accord,36.0,4,107.0,75,2205,14.5,82,Japan,427,OH
134,Honda Civic (auto),32.0,4,91.0,67,1965,15.7,82,Japan,430,TEXAS
22,Datsun 310 GX,38.0,4,91.0,67,1995,16.2,82,Japan,431,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
110,Ford Mustang GL,27.0,4,140.0,86,2790,15.6,82,US,439,OH

In [ ]:
print("------After Sorting by quantity and Car -------")
df_cars.sort_values(by=['quantity','Car'], ascending=[False,True])

------After Sorting by quantity and Car -------

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
110,Ford Mustang GL,27.0,4,140.0,86,2790,15.6,82,US,439,OH
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
22,Datsun 310 GX,38.0,4,91.0,67,1995,16.2,82,Japan,431,NJ
134,Honda Civic (auto),32.0,4,91.0,67,1965,15.7,82,Japan,430,TEXAS
128,Honda Accord,36.0,4,107.0,75,2205,14.5,82,Japan,427,OH
...,...,...,...,...,...,...,...,...,...,...,...
121,Ford Ranger,28.0,4,120.0,79,2625,18.6,82,US,7,DALLAS
130,Honda Accord LX,29.5,4,98.0,68,2135,16.6,78,Japan,7,NJ
147,Mazda GLC Deluxe,34.1,4,86.0,65,1975,15.2,79,Japan,7,NJ
112,Ford Mustang II 2+2,25.5,4,140.0,89,2755,15.8,77,US,5,NJ
123,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US,5,OH

# **Submission Instructions:**
Include the following deliverables in your submission -

- Submit your completed Python program file(s) with appropriate comments and - any additional instructions if required,
- Using the Start Assignment button in the top-right corner of the assignment page in Canvas.